# Generated by Django 2.1.3 on 2018-11-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
